openapi: 3.0.2
servers: []
info:
  version: "0.1"
  title: GA4GH Beacon Interactor Default Schema
  description: >-
    Schema for interactor to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    This object contains info related to the subject from where the variants are found in a study. 
    It includes taxon id and any other relevant information about it, including maybe links or id 
    of genome assemblies and ref seqs associated to this species that are available in the Beacon 
    and that are used for variant identification (location)
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    level_severity:
      description: |
        Level/severity ontology when and as applicable to phenotype observed. Value from TBD, e.g ”mild”
      type: object
      properties:
        level_severity:
          description: |
            Level/severity ontology when and as applicable to phenotype observed. Value from TBD, e.g ”mild”
          type: string
          enum: 
            - TBD #todo # Source TBD
          example: 'severe'
    dateOfOnset:
      description: |
        Date of onset/observation of phenotype, in (ISO8601 duration format)
      type: object
      properties:
        dateOfOnset:
          description: |
            Date of onset/observation of phenotype, in (ISO8601 duration format)
          type: string
          example: 'P3Y6M4DT12H30M5S' ##todo to be confirmed
    Disease:
      description: |
        Lisf of disease(s) been diagnosed to the subject, defined by diseaseID, age of onset, 
        stage, level/severity, outcome and the presence of family history
      type: object
      properties:
        diseaseId:
          description: |
            Disease identifier. Value from ICD10 disease codes or ontology terms 
            from disease ontologies such as HPO, OMIM, Orphanet, MONDO, e.g. 
            lactose intolerance (HP:0004789, ICD10CM:E73).
          type: string
          example:
            - 'HP:0004789'
            - 'ICD10CM:E73'
        ageOfOnset:
          $ref: 'https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/master/common.yaml#/components/schemas/Age'
        stage:
          description: |
            Ontology value from Ontology for General Medical Science or Disease 
            Stage Qualifier ontology (NCIT:C28108), e.g. acute onset (OGMS:0000119)
          type: string
          example: 'OGMS:0000119'
        level_severity: #todo '/'' or 'or'
          $ref: '#/components/schemas/level_severity'
        outcome:
          description: |
             Outcome of passed acute diseases. Value from TBD, eg. ”fatal”
          type: string
          enum:
            - TBD #todo
          example: 'fatal'
        familyHistory:
          description: |
            Boolean indicating determined or self-reported presence of family 
            history of the disease.
          type: boolean
          example: True
    treatments:
      description: |
        List of treatment(s) been prescribed/administered to subject, defined by treatment ID), date and age of onset, dose, schedule and duration.
      type: object
      properties:
        treatmentId:
          description: |
            Treatment ID. Value from TBD
          type: string
          example: #todo
        dateAtOnset:
          $ref: '#/components/schemas/dateOfOnset'
        ageAtOnset:
          $ref: 'https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/master/common.yaml#/components/schemas/Age'
    Pedigree:
      description: |
        Pedigree studie(s) in which the individual is part of.
      type: object
      properties:
        pedigreeID:
          description: |
            Pedigree identifier.
          type: string
          example: 'Pedigree1001'
        pedigreeRole:
          description: |
            Pedigree role, defined as relationship to proband. Value from HL7 
            code for family relationship or Relationship to Proband ontology 
            (ERO:0002112), e.g. ERO:0002041 (identical twin relationship).
          type: string
          example: 'ERO:0002041'
        numIndTested:
          description: |
            Number of individuals in pedigree, including proband.
          type: integer
          format: int64
          minimum: 0
          example: 5
    phenotypicFeatures:
      description: |
        List of phenotypic feature(s) observed in the subject, 
        defined by phenotype, age of onset and level/ severity. 
      type: object
      properties:
        phenotypeId:
          description: |
            Phenotypic feature observed. 
            Value from Human Phenotype Ontology (HPO) or other phenotype ontology.
          type: string
        dateOfOnset:
          description: |
            Date of onset/observation of phenotype, in (ISO8601 duration format)
          type: string
          example: 'P3Y6M4DT12H30M5S' ##todo to be confirmed
        ageOfOnset:
          $ref: 'https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/master/common.yaml#/components/schemas/Age'
        level_severity: #todo '/'' or 'or'
          $ref: '#/components/schemas/level_severity'
    Interactor:
      description: |
        Todo
      type: object
      properties:
        relationType:
          description: |
            Ontology value for ype of relation with Subject e.g ”host”, ”pathogen”, ”commensal”, etc
          type: string
          example: 'host'
        subjectId:
          description: |
            Subject identifier (external accession or internal ID).
          type: string
          example: P0001
        taxonId:
          description: |
            Reference taxon ID for subject organism
          type: string
          example: 'human, animal or plant'
        sex:
          description: |
            Sex of subject.
            Value from NCIT General Qualifier (NCIT:C27993) ontology: UNKNOWN 
            (not assessed or not available) (NCIT:C17998), FEMALE (NCIT:C46113), 
            MALE, (NCIT:C46112) or OTHER SEX (NCIT:C45908).
          type: string
          enum: 
            - NCIT:C17998
            - NCIT:C46113
            - NCIT:C46112
            - NCIT:C45908
          example: 'NCIT:C17998'
        ethnicity:
          description: |
            Ethnic background of subject. Value from NCIT Race ontology 
            (NCIT:C17049), e.g. NCIT:C126531 (Latin American).
          type: string
          example: 'NCIT:C126531'
        geographicOrigin:
          description: |
            Subject's country or region of origin (birthplace or residence 
            place regardless of ethnic origin). Value from GAZ Geographic 
            Location ontology (GAZ:00000448), e.g. GAZ:00002459 (United States 
            of America).
          type: string
          example: 'GAZ:00002459'
        diseases:
          description: |
            List of disease(s) been diagnosed to the individual, defined by 
            disease ICD10 code, optionally other disease ontology ID(s), age of 
            onset, stage and the presence of family history.
          type: array
          items:
            $ref: '#/components/schemas/Disease'
        pedigrees:
          type: array
          items:
            $ref: '#/components/schemas/Pedigree'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue3